// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eguoekxuwnerumhehheo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVndW9la3h1d25lcnVtaGVoaGVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MDI3MzYsImV4cCI6MjA3MzE3ODczNn0.FxBUcfmmTaCtr74Q2RW79c9hirwyLzJU_z-GG1m5P9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});